import type { EnemyDef } from '@/types';

export const ENEMIES: Record<string, EnemyDef> = {
  bolKregoslupa: {
    id: 'bolKregoslupa',
    name: 'Ból Kręgosłupa',
    level: 1,
    stats: { hp: 45, mp: 10, atk: 12, def: 8, mag: 6, spd: 7, lck: 4 },
    skills: ['attack', 'backPain'],
    sprite: 'enemy_bolKregoslupa',
    xp: 25,
    ai: 'weakest',
  },
  slacki: {
    id: 'slacki',
    name: 'Nieprzeczytane Slacki',
    level: 2,
    stats: { hp: 65, mp: 25, atk: 10, def: 10, mag: 14, spd: 11, lck: 8 },
    skills: ['attack', 'slackPing', 'stressDebuff'],
    sprite: 'enemy_slacki',
    xp: 40,
    ai: 'random',
  },

  // Later-chapter stubs (ready for expansion)
  sasiadSzkodnik: {
    id: 'sasiadSzkodnik',
    name: 'Sąsiad Szkodnik',
    level: 4,
    stats: { hp: 160, mp: 30, atk: 18, def: 14, mag: 12, spd: 9, lck: 6 },
    skills: ['attack', 'stressDebuff'],
    sprite: 'enemy_sasiadSzkodnik',
    xp: 120,
    boss: true,
  },
  autoTuneHipster: {
    id: 'autoTuneHipster',
    name: 'Auto-Tune Hipster',
    level: 5,
    stats: { hp: 95, mp: 40, atk: 14, def: 11, mag: 20, spd: 14, lck: 12 },
    skills: ['attack', 'slackPing'],
    sprite: 'enemy_autoTuneHipster',
    xp: 75,
  },
  drogiePiwo: {
    id: 'drogiePiwo',
    name: 'Zbyt Drogie Piwo',
    level: 5,
    stats: { hp: 110, mp: 15, atk: 16, def: 16, mag: 10, spd: 8, lck: 5 },
    skills: ['attack'],
    sprite: 'enemy_drogiePiwo',
    xp: 80,
  },
  straznik: {
    id: 'straznik',
    name: 'Strażnik Miejski',
    level: 6,
    stats: { hp: 120, mp: 20, atk: 20, def: 18, mag: 10, spd: 11, lck: 8 },
    skills: ['attack', 'stressDebuff'],
    sprite: 'enemy_straznik',
    xp: 95,
  },
  kark: {
    id: 'kark',
    name: 'Szef Ochrony "Kark"',
    level: 7,
    stats: { hp: 280, mp: 20, atk: 28, def: 24, mag: 8, spd: 9, lck: 10 },
    skills: ['attack'],
    sprite: 'enemy_kark',
    xp: 250,
    boss: true,
    immune: { physical: true, untilStatus: ['stun'] },
  },
  panJanusz: {
    id: 'panJanusz',
    name: 'Pan Janusz (Komendant)',
    level: 10,
    stats: { hp: 800, mp: 100, atk: 35, def: 28, mag: 30, spd: 14, lck: 15 },
    skills: ['attack', 'stressDebuff'],
    sprite: 'enemy_panJanusz',
    xp: 1000,
    boss: true,
    phases: [
      { when: { hpBelow: 0.66 }, say: 'Co tu się dzieje?! Nielegalne obozowisko! Mandat 5000 zł!' },
      { when: { hpBelow: 0.33 }, say: 'Jutro poniedziałek 8:00 rano! Wszyscy do Excela!' },
    ],
  },
  kredyt: {
    id: 'kredyt',
    name: 'Kredyt na 30 Lat',
    level: 9,
    stats: { hp: 240, mp: 40, atk: 30, def: 25, mag: 15, spd: 10, lck: 5 },
    skills: ['attack'],
    sprite: 'enemy_kredyt',
    xp: 180,
  },
  audyt: {
    id: 'audyt',
    name: 'Audyt Korporacyjny',
    level: 9,
    stats: { hp: 200, mp: 60, atk: 22, def: 20, mag: 28, spd: 13, lck: 10 },
    skills: ['attack', 'stressDebuff'],
    sprite: 'enemy_audyt',
    xp: 180,
  },
  rwaKulszowa: {
    id: 'rwaKulszowa',
    name: 'Rwa Kulszowa',
    level: 9,
    stats: { hp: 180, mp: 30, atk: 32, def: 18, mag: 16, spd: 8, lck: 12 },
    skills: ['attack', 'backPain'],
    sprite: 'enemy_rwaKulszowa',
    xp: 180,
  },
};
