import type { HeroDef, HeroId } from '@/types';
import { PAL } from '@/config';

export const HEROES: Record<HeroId, HeroDef> = {
  danny: {
    id: 'danny', name: 'Danny', fullName: 'DANIEL G.', className: 'The Tank', role: 'High HP / Physical Defense',
    signature: 'steelWall', skills: ['steelWall', 'shakerSlam'],
    base: { hp: 160, mp: 30, atk: 16, def: 18, mag: 6, spd: 8, lck: 6 },
    growth: { hp: 18, mp: 2, atk: 2, def: 3, mag: 0.5, spd: 0.5, lck: 0.5 },
    items: ['shield', 'gauntlets', 'shaker'],
    leaderQuote: 'No i kurwa prawidłowo. Ktoś musi brać na klatę ciosy, jak chłopaki znowu odpalą manianę. Łapcie za sprzęt i zbieramy ekipę!',
    leaderBonus: { label: '+10% DEF drużyny', effect: { id: 'lead_danny', name: 'Klata Lidera', kind: 'statMod', stat: 'def', value: 0.1, turns: -1 } },
    color: PAL.fire,
  },
  alior: {
    id: 'alior', name: 'Alior', fullName: 'KRZYSZTOF K.', className: 'The Gamer', role: 'Buff / Crowd Control',
    signature: 'frameTrap', skills: ['frameTrap', 'comboString'],
    base: { hp: 110, mp: 85, atk: 12, def: 10, mag: 14, spd: 13, lck: 9 },
    growth: { hp: 11, mp: 6, atk: 1.5, def: 1.2, mag: 2, spd: 1.2, lck: 1 },
    items: ['controller', 'cartridge', 'goggles'],
    leaderQuote: '30 FPS? Zapomnij, mordo. Zaraz rozpiszę optymalną trasę w Google Maps i wyciągniemy z tej nocy 60 ramek na sekundę bez żadnego laga!',
    leaderBonus: { label: '+10% SPD drużyny (60 FPS)', effect: { id: 'lead_alior', name: '60 FPS', kind: 'statMod', stat: 'spd', value: 0.1, turns: -1 } },
    color: PAL.green,
  },
  lisu: {
    id: 'lisu', name: 'Lisu', fullName: 'LISU', className: 'The Swift Scout', role: 'High Speed / Critical Strikes',
    signature: 'smokeScreen', skills: ['smokeScreen', 'backstab'],
    base: { hp: 100, mp: 50, atk: 15, def: 9, mag: 8, spd: 18, lck: 16 },
    growth: { hp: 10, mp: 3, atk: 2, def: 1, mag: 1, spd: 2, lck: 1.5 },
    items: ['binoculars', 'fox', 'sneakers'],
    leaderQuote: 'Cicho, spokojnie... Przemkniemy tyłami, ominiemy ochronę pod klubem i nikt nawet nie zauważy, kiedy wyciągniemy resztę z baru.',
    leaderBonus: { label: '+10% LCK (kryty)', effect: { id: 'lead_lisu', name: 'Cień Lisa', kind: 'statMod', stat: 'lck', value: 0.25, turns: -1 } },
    color: PAL.red,
  },
  barti: {
    id: 'barti', name: 'Barti', fullName: 'BARTEK K.', className: 'The Vinyl Bard', role: 'AOE Magic / Support',
    signature: 'bassBlast', skills: ['bassBlast', 'scratch'],
    base: { hp: 105, mp: 90, atk: 10, def: 10, mag: 17, spd: 11, lck: 10 },
    growth: { hp: 10, mp: 7, atk: 1, def: 1, mag: 2.5, spd: 1, lck: 1 },
    items: ['vinyl', 'turntable', 'speaker'],
    leaderQuote: 'Czekaj, wrzucę tylko na gramofon klasyka od Kalibra 44. Bez tłustego bitu i dobrej stopy nigdzie nie idę!',
    leaderBonus: { label: '+10% ATK (tłusty bit)', effect: { id: 'lead_barti', name: 'Tłusty Bit', kind: 'statMod', stat: 'atk', value: 0.1, turns: -1 } },
    color: PAL.denim,
  },
  oziem: {
    id: 'oziem', name: 'Oziem', fullName: 'MARCIN O.', className: 'The Bushcraft Expert', role: 'Support / Sustained Healing',
    signature: 'wildernessSurvival', skills: ['wildernessSurvival', 'multitool'],
    base: { hp: 125, mp: 75, atk: 13, def: 13, mag: 14, spd: 10, lck: 9 },
    growth: { hp: 13, mp: 5, atk: 1.5, def: 1.5, mag: 2, spd: 1, lck: 1 },
    items: ['rope', 'multitool', 'campfire'],
    leaderQuote: 'Byle nie do lokalu z klimatyzacją... Moje krzesiwo, tinderbox i hamak już czekają w plecaku. Czas spalić trochę drewna!',
    leaderBonus: { label: 'Regeneracja 3% HP / turę', effect: { id: 'lead_oziem', name: 'Leśny Oddech', kind: 'regen', value: 0.03, turns: -1 } },
    color: PAL.teal,
  },
  luki: {
    id: 'luki', name: 'Łuki', fullName: 'ŁUKASZ', className: 'The Aquatic Instructor', role: 'Purifier / Clutch Healer',
    signature: 'aquaRescue', skills: ['aquaRescue', 'lifebuoyThrow'],
    base: { hp: 115, mp: 80, atk: 12, def: 11, mag: 15, spd: 11, lck: 10 },
    growth: { hp: 12, mp: 6, atk: 1.2, def: 1.2, mag: 2.2, spd: 1, lck: 1 },
    items: ['divingGoggles', 'lifebuoy', 'backpack'],
    leaderQuote: 'Jak ktoś po trzech piwach wpadnie do rzeki albo straci balans przy ognisku, osobiście go wyciągam na brzeg. Idziemy!',
    leaderBonus: { label: '+10% MAG (ratownik)', effect: { id: 'lead_luki', name: 'Ratownik', kind: 'statMod', stat: 'mag', value: 0.1, turns: -1 } },
    color: PAL.cyan,
  },
};
